[app]
name = "Cycle"
version = "1.2.0"
description = "Дневник тренировок и планирования"

[build.android]
package = "com.nelinmatvey.cycle"
version_code = 120

[build.ios]
bundle_id = "com.nelinmatvey.cycle"

[build.macos]
bundle_id = "com.nelinmatvey.cycle"

[build.windows]
# Наследует name, version и description из [app]

[build.linux]
# Наследует name, version и description из [app]