[build.android]
app_name = "Cycle"
package_name = "com.nelinmatvey.cycle"
version = "1.1.3"
min_sdk_version = 21
target_sdk_version = 34

[build.ios]
app_name = "Cycle"
bundle_name = "com.nelinmatvey.cycle"
version = "1.1.3"

[build.windows]
app_name = "Cycle"

[build.linux]
app_name = "Cycle"

[build.macos]
app_name = "Cycle"