[project]
name = "cycle"
version = "1.3.7"
description = "Дневник тренировок и планирования"
dependencies = []

[tool.flet]
product = "Cycle"                     # Имя для иконки на экране телефона
org = "com.nelinmatvey"               # Домен организации
build_number = 1

[tool.flet.android]
package = "com.nelinmatvey.cycle"

[tool.flet.ios]
bundle_id = "com.nelinmatvey.cycle"

[tool.flet.macos]
bundle_id = "com.nelinmatvey.cycle"

[tool.flet.windows]
# Автоматически наследует

[tool.flet.linux]
# Автоматически наследует
